logging:
  file: ../logs/demo.log
  level:com.dragon.study.spring.boot: DEBUG

spring:
  datasource:
    druid:
      url: jdbc:mysql://132.232.123.76:3306/myshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 5.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    type-aliases-package: com.team.facade.pojo
    mapper-locations: classpath:mapper/*.xml

